### ISSUE TITLE
build fails when using prerender 

### ISSUE THREAD

**Issue by mayank99** [preactjs/preset-vite#110]
Trying out the prerender plugin with version 2.8.1, I cannot get the build to pass.

```console
x Build failed in 407ms
error during build:
TypeError: [preact:prerender] d is not a function
    at i (file:///<repo>/node_modules/@preact/preset-vite/headless-prerender/prerender-DWVaPvWr.js:1:262)
    at Module.g (file:///<repo>/node_modules/@preact/preset-vite/headless-prerender/prerender-DWVaPvWr.js:1:437)
    at file:///<repo>/node_modules/@preact/preset-vite/headless-prerender/main-DSgznFuN.js:1:16171
```

See repro: https://stackblitz.com/edit/vitejs-vite-ybgooe?file=src%2Fmain.jsx,vite.config.js&terminal=build

**Comment by rschristian** [comment]
Can you reproduce outside of stackblitz?

**Comment by rschristian** [comment]
Sorry for the headache!
