### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module @preact\preset-vite when scaffolding vanilla preact

### ISSUE THREAD

**Issue by r42-leon** [preactjs/preset-vite#21]
When using `npm init vite` with the `preact` framework and `preact` (vanilla js) variant, I get the following error when starting the development server after npm install:

```
error when starting dev server:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: E:\Javascript\starter-vite-preact\node_modules\@preact\preset-vite\dist\index.js
require() of ES modules is not supported.
require() of E:\Javascript\starter-vite-preact\node_modules\@preact\preset-vite\dist\index.js from E:\Javascript\starter-vite-preact\vite.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from E:\Random42\Javascript\starter-vite-preact\node_modules\@preact\preset-vite\package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Object.require.extensions.<computed> [as .js] (E:\Javascript\starter-vite-preact\node_modules\vite\dist\node\chunks\dep-36bf480c.js:77286:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Random42\Javascript\starter-vite-preact\vite.config.js:30:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions.<computed> [as .js] (E:\Javascript\starter-vite-preact\node_modules\vite\dist\node\chunks\dep-36bf480c.js:77283:20)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Deps versions are
```
    "preact": "^10.5.13"
    "@preact/preset-vite": "^2.0.0",
    "vite": "^2.5.4"
```

**Comment by piotr-cz** [comment]
Same here.
The error goes away after adding `"type": "module"` in package.json, however VSCode started to compain now (*Cannot find module '@preact/preset-vite' or its corresponding type declarations.*).

I didn't understand why it's not been set in the templates (reference: https://github.com/vitejs/vite/pull/4293)

**Comment by marvinhagemeister** [comment]
Awesome, thanks for letting us know! Just published `v2.1.2` which addresses this issue 👍

**Comment by piotr-cz** [comment]
@marvinhagemeister Thank You!

**Comment by WolfCodeBind** [comment]
I am new to vite and so I am receiving the same error can you pls help me with it? IDK how to install the different version of vite.
I want to create a project by using the command `npm init @vitejs/app` but it's giving me the error that says. 
@vitejs/create-app is deprecated, use npm init vite instead

```
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ME/.npm/_npx/9c7583f20b80c4d1/node_modules/create-vite/index.js
require() of ES modules is not supported.
require() of /home/ME/.npm/_npx/9c7583f20b80c4d1/node_modules/create-vite/index.js from /home/ME/.npm/_npx/9c7583f20b80c4d1/node_modules/@vitejs/create-app/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/ME/.npm/_npx/9c7583f20b80c4d1/node_modules/create-vite/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/MEnpm/_npx/9c7583f20b80c4d1/node_modules/create-vite/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ME/.npm/_npx/9c7583f20b80c4d1/node_modules/@vitejs/create-app/index.js:43:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code 1
npm ERR! path /home/ME/Desktop/Web-Based/animation
npm ERR! command failed
npm ERR! command sh -c create-app

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ME/.npm/_logs/2022-07-30T10_26_25_490Z-debug-0.log
```

but then I tried to use the command that is provided above `npm init vite` and then I got some other error. 

```
Need to install the following packages:
  create-vite
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'create-vite@3.0.0',
npm WARN EBADENGINE   required: { node: '>=14.18.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
file:///home/ME/.npm/_npx/2c4a09cdd3a6d615/node_modules/create-vite/index.js:296
  return targetDir?.trim().replace(/\/+$/g, '')
                   ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/ME/Desktop/Web-Based/animation
npm ERR! command failed
npm ERR! command sh -c create-vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daemon_surge/.npm/_logs/2022-07-30T10_29_47_889Z-debug-0.log

```

**Comment by marvinhagemeister** [comment]
@WolfCodeBind the issue doesn't seem to be related to Preact's preset for vite as you're not using it anywhere. You seem to be using vite on its own without our preset. In the future I'd recommend to report vite-related problems over at the [vite's issue tracker](https://github.com/vitejs/vite). That's the correct place to report them and they have more bandwidth to help with general vite issues.

Nonetheless to help you out, the error you're seeing there describes the problem and solution to it.

This is telling you that you're node version is not supported:

```txt
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'create-vite@3.0.0',
npm WARN EBADENGINE   required: { node: '>=14.18.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
```

It tells you that your current node version is `12.22.9` and that vite requires node `14.18.0` at minimum. You can verify which node version you're using by running `node -v` in your terminal. To resolve this error, update your node version. At the time of this writing the current stable node version is `16.16.0`.

**Comment by liuliuboy** [comment]
Try this instead:

$npm create vite@latest
