### ISSUE TITLE
Tests fail in CI, succeed locally

### ISSUE THREAD

**Issue by zgoda** [preactjs/preset-vite#31]
The tests are [throwing in CI](https://github.com/zgoda/curingtables/runs/4194005166?check_suite_focus=true), but run fine in local env.

I'm running test suite using GH Actions. Interesing part:

```
    Cannot find module 'preact-render-to-string/jsx' from 'node_modules/jest-preset-preact/src/serializer.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/jest-preset-preact/src/serializer.js:1:106)
```

Quite strange, isn't it?

**Comment by zgoda** [comment]
Ugh, PEBKAC.
