### ISSUE TITLE
Ambiguous import error with yarn pnp

### ISSUE THREAD

**Issue by not-ivy** [preactjs/preset-vite#74]
When I tried to start the dev server with yarn v3 and noderLinker set to pnp, this error appears:

```
PS C:\Users\user\Documents\sources\appt-frontend> yarn dev
failed to load config from C:\Users\user\Documents\sources\appt-frontend\vite.config.ts
error when starting dev server:
Error: @preact/preset-vite tried to access @babel/core (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

Required package: @babel/core (via "@babel\core\package.json")
Required by: @preact/preset-vite@virtual:477b2cede8cf0bfea85632ec9f519cda9b54e21d6ebc7600dbb0c5d62a8a94da58a04b136c769fefb52b9ee632e2542060b59c08a961728f02ec197b6c2f7b9c#npm:2.5.0 (via C:\Users\user\Documents\sources\appt-frontend\.yarn\__virtual__\@preact-preset-vite-virtual-839bfe540e\0\cache\@preact-preset-vite-npm-2.5.0-ba38e18ed0-9ab9180b0e.zip\node_modules\@preact\preset-vite\dist\esm\index.mjs)
Ancestor breaking the chain: placeholderpt@workspace:.


    at makeError (C:\Users\user\Documents\sources\appt-frontend\.pnp.cjs:11616:34)
    at resolveToUnqualified (C:\Users\user\Documents\sources\appt-frontend\.pnp.cjs:13275:21)
    at Object.resolveToUnqualified (C:\Users\user\Documents\sources\appt-frontend\.pnp.cjs:13518:26)
    at resolve$1 (file:///C:/Users/user/Documents/sources/appt-frontend/.pnp.loader.mjs:1981:31)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by rschristian** [comment]
You may need to manually add `@babel/core` to your project's dependencies if Yarn PNP isn't going to install peer deps when they cannot be found.

**Comment by tonisives** [comment]
I also had the same issue. Don't have this issue when using normal react preset

**Comment by rschristian** [comment]
Closing this out, we're not doing anything special or odd with our peer deps here.
