### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/david/Documents/www1/testin/testin-platform/node_modules/vite/bin/vite.js not supported.

### ISSUE THREAD

**Issue by DavidKFL** [preactjs/preset-vite#84]
使用pm2 管理进程时提示这个错误。
pm2配置：
{
  "name": "testin-platform",
  "script"          : "./node_modules/vite/bin/vite.js",
  "watch"       : false,
  "merge_logs"      : true,
  "error_file"      : "pm2_log/error/err.log",
  "out_file"        : "pm2_log/out/out.log",
  "log_date_format" : "YYYY-MM-DD HH:mm Z",
  "instances": 2
}

vite.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename vite.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/david/Documents/www1/testin/testin-platform/node_modules/vite/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:295:23
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:21:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:186:13)
    at WriteStream.emit (node:events:520:28)
    at FSReqCallback.oncomplete (node:fs:188:23)

**Comment by rschristian** [comment]
Can you please provide a reproduction? This doesn't look to be related to this plugin with what you've given.

**Comment by DavidKFL** [comment]
> Can you please provide a reproduction? This doesn't look to be related to this plugin with what you've given.
"vite": "^3.2.7"


import { defineConfig, loadEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'
import eslintPlugin from 'vite-plugin-eslint'

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    // 二级路由运维配置
    // base: loadEnv(mode, process.cwd()).VITE_USER_NODE_ENV === 'development' ? '/platform/' : '/',
    base: '/platform/',
    plugins: [
      vue(),
      eslintPlugin({ include: ['src/**/*.js', 'src/**/*.vue', 'src/*.js', 'src/*.vue'] })
    ],
    server: {
      host: '0.0.0.0',
      port: 8080,
      open: false
    },
    resolve: {
      // 配置vite别名
      alias: [
        { find: '@', replacement: resolve(__dirname, 'src') },
        // vue-i18n.esm-bundler.js:39 You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
        { find: 'vue-i18n', replacement: 'vue-i18n/dist/vue-i18n.cjs.js' }
      ]
    },
    build: {
      // 浏览器兼容性  "esnext"|"modules"
      target: 'esnext',
      // 启用/禁用 CSS 代码拆分
      cssCodeSplit: true,
      sourcemap: false,
      // 调整包告警的大小
      chunkSizeWarningLimit: 1500,
      minify: 'terser',
      terserOptions: {
        compress: {
          // 生产环境时移除console
          drop_console: true,
          drop_debugger: true
        }
      },
      rollupOptions: {
        // 代码分解
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              return id.toString().split('node_modules/')[1].split('/')[0].toString()
            }
          },
          chunkFileNames: (chunkInfo) => {
            const facadeModuleId = chunkInfo.facadeModuleId ? chunkInfo.facadeModuleId.split('/') : []
            const fileName = facadeModuleId[facadeModuleId.length - 2] || '[name]'
            return `js/${fileName}/[name].[hash].js`
          }
        }
      }
    }
  }
})
